/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = function (knex) {
  return knex("canciones").del()
    .then(function () {
      return knex("canciones").insert([
        { nombre_cancion: "Carretera Perdida", id_musico: 1, id_disco: 1 },
        { nombre_cancion: "Mincho Bar", id_musico: 1, id_disco: 2 },
        { nombre_cancion: "La Plegaria del Cuchillo", id_musico: 1, id_disco: 3 },
        { nombre_cancion: "A Cartas Vistas", id_musico: 1, id_disco: 4 },
        { nombre_cancion: "Buitres", id_musico: 1, id_disco: 1 },
        { nombre_cancion: "El Tercer Deseo", id_musico: 1, id_disco: 4 },
        { nombre_cancion: "Besos", id_musico: 1, id_disco: 2 },
        { nombre_cancion: "Yo No Voy a Morir", id_musico: 1, id_disco: 1 },
        { nombre_cancion: "Afuera la Lluvia", id_musico: 1, id_disco: 5 },
        { nombre_cancion: "Condenado el Corazón", id_musico: 1, id_disco: 6 },
        { nombre_cancion: "Amores Como el Nuestro", id_musico: 2, id_disco: 7 },
        { nombre_cancion: "Polvo de Estrellas", id_musico: 2, id_disco: 8 },
        { nombre_cancion: "Sin Sentimiento", id_musico: 2, id_disco: 9 },
        { nombre_cancion: "La Piscina", id_musico: 2, id_disco: 10 },
        { nombre_cancion: "Telepatía", id_musico: 2, id_disco: 11 },
        { nombre_cancion: "Hechizo de Luna", id_musico: 2, id_disco: 8 },
        { nombre_cancion: "Sobredosis", id_musico: 2, id_disco: 12 },
        { nombre_cancion: "Mi Mundo, Tú", id_musico: 2, id_disco: 13 },
        { nombre_cancion: "Un Terremoto de Amor", id_musico: 2, id_disco: 14 },
        { nombre_cancion: "Piénsalo Dos Veces", id_musico: 2, id_disco: 15 },
        { nombre_cancion: "Mi País", id_musico: 3, id_disco: 16 },
        { nombre_cancion: "Muriendo de Plena", id_musico: 3, id_disco: 16 },
        { nombre_cancion: "Cha Cha, Muchacha", id_musico: 3, id_disco: 16 },
        { nombre_cancion: "Candombe para Gardel", id_musico: 3, id_disco: 17 },
        { nombre_cancion: "Las Manzanas", id_musico: 3, id_disco: 18 },
        { nombre_cancion: "Será Posible", id_musico: 3, id_disco: 19 },
        { nombre_cancion: "Ayer Te Vi", id_musico: 3, id_disco: 20 },
        { nombre_cancion: "Terapia de Murga", id_musico: 3, id_disco: 19 },
        { nombre_cancion: "Solo Se Trata de Vivir", id_musico: 3, id_disco: 21 },
        { nombre_cancion: "Amandote", id_musico: 4, id_disco: 22 },
        { nombre_cancion: "Ciega, Sordomuda", id_musico: 4, id_disco: 23 },
        { nombre_cancion: "Inevitable", id_musico: 4, id_disco: 23 },
        { nombre_cancion: "Antologia", id_musico: 4, id_disco: 23 },
        { nombre_cancion: "Estoy Aquí", id_musico: 4, id_disco: 24 },
        { nombre_cancion: "Pies Descalzos, Sueños Blancos", id_musico: 4, id_disco: 24 },
        { nombre_cancion: "Ojos Asi", id_musico: 4, id_disco: 24 },
        { nombre_cancion: "Si Te Vas", id_musico: 4, id_disco: 23 },
        { nombre_cancion: "Loba", id_musico: 4, id_disco: 23 },
        { nombre_cancion: "Donde Están Los Ladrones", id_musico: 4, id_disco: 25 },
        { nombre_cancion: "Que Me Quedes Tú", id_musico: 5, id_disco: 23 },
        { nombre_cancion: "Con Altura", id_musico: 5, id_disco: 26 },
        { nombre_cancion: "Bizcochito", id_musico: 5, id_disco: 27 },
        { nombre_cancion: "Despechá", id_musico: 5, id_disco: 28 },
        { nombre_cancion: "La Fama", id_musico: 5, id_disco: 28 },
        { nombre_cancion: "Malamente", id_musico: 5, id_disco: 28 },
        { nombre_cancion: "Saoko", id_musico: 5, id_disco: 29 },
        { nombre_cancion: "Beso", id_musico: 5, id_disco: 28 },
        { nombre_cancion: "Pienso en tu mirá", id_musico: 5, id_disco: 30 },
        { nombre_cancion: "Tuya", id_musico: 5, id_disco: 29 },
        { nombre_cancion: "Llylm", id_musico: 6, id_disco: 31 },
        { nombre_cancion: "Lo Siento", id_musico: 6, id_disco: 32 },
        { nombre_cancion: "A Ella", id_musico: 6, id_disco: 33 },
        { nombre_cancion: "Solo Tu y Yo", id_musico: 6, id_disco: 34 },
        { nombre_cancion: "Inocente", id_musico: 6, id_disco: 35 },
        { nombre_cancion: "En un lugar un niño", id_musico: 6, id_disco: 36 },
        { nombre_cancion: "Oncemil", id_musico: 6, id_disco: 37 },
        { nombre_cancion: "Que Digan Lo Que Quieran", id_musico: 6, id_disco: 38 },
        { nombre_cancion: "Mi Primer Amor", id_musico: 6, id_disco: 39 },
        { nombre_cancion: "Amarte No Se Olvida", id_musico: 7, id_disco: 40 },
        { nombre_cancion: "Santa Noche", id_musico: 7, id_disco: 41 },
        { nombre_cancion: "Paint It Black", id_musico: 7, id_disco: 42 },
        { nombre_cancion: "Sympathy For The Devil", id_musico: 7, id_disco: 43 },
        { nombre_cancion: "Start Me Up", id_musico: 7, id_disco: 44 },
        { nombre_cancion: "Angie", id_musico: 7, id_disco: 45 },
        { nombre_cancion: "Under My Thumb", id_musico: 7, id_disco: 46 },
        { nombre_cancion: "You Can't Always Get What You Want", id_musico: 7, id_disco: 47 },
        { nombre_cancion: "Ruby Tuesday", id_musico: 7, id_disco: 44 },
        { nombre_cancion: "Wild Horses", id_musico: 7, id_disco: 48 },
        { nombre_cancion: "Satisfaction", id_musico: 8, id_disco: 49 },
        { nombre_cancion: "Brown Sugar", id_musico: 8, id_disco: 50 },
        { nombre_cancion: "Leave The Door Open", id_musico: 8, id_disco: 50 },
        { nombre_cancion: "Smokin Out The Window", id_musico: 8, id_disco: 50 },
        { nombre_cancion: "After Last Night Night", id_musico: 8, id_disco: 50 },
        { nombre_cancion: "Skate", id_musico: 8, id_disco: 50 },
        { nombre_cancion: "Love's Train", id_musico: 8, id_disco: 50 },
        { nombre_cancion: "Fly As Me", id_musico: 8, id_disco: 50 },
        { nombre_cancion: "Blast Off", id_musico: 8, id_disco: 50 },
        { nombre_cancion: "Put On A Smile", id_musico: 8, id_disco: 50 },
        { nombre_cancion: "777", id_musico: 9, id_disco: 51 },
        { nombre_cancion: "Silk Sonic Intro", id_musico: 9, id_disco: 51 },
        { nombre_cancion: "Velha Infancia", id_musico: 9, id_disco: 51 },
        { nombre_cancion: "Já Sei Namorar", id_musico: 9, id_disco: 51 },
        { nombre_cancion: "Carnavália", id_musico: 9, id_disco: 51 },
        { nombre_cancion: "Passe Em Casa", id_musico: 9, id_disco: 51 },
        { nombre_cancion: "É Vocé", id_musico: 9, id_disco: 51 },
        { nombre_cancion: "Diáspora", id_musico: 9, id_disco: 51 },
        { nombre_cancion: "Um a Um", id_musico: 9, id_disco: 51 },
        { nombre_cancion: "Carnalismo", id_musico: 10, id_disco: 52 },
        { nombre_cancion: "Anjo de Guarda", id_musico: 10, id_disco: 52 },
        { nombre_cancion: "O Amor É Feio", id_musico: 10, id_disco: 53 },
        { nombre_cancion: "Milagro", id_musico: 10, id_disco: 54 },
        { nombre_cancion: "Santamarta", id_musico: 10, id_disco: 55 },
        { nombre_cancion: "Zumba Que Zumba-En Vivo", id_musico: 10, id_disco: 56 },
        { nombre_cancion: "La Martín Aranda", id_musico: 10, id_disco: 55 },
        { nombre_cancion: "Ocho Letras", id_musico: 10, id_disco: 57 },
        { nombre_cancion: "Peón Rural", id_musico: 10, id_disco: 56 },
        { nombre_cancion: "Cuando Cante el Gallo Azul", id_musico: 10, id_disco: 56 },
        { nombre_cancion: "Algo Habrán Hecho", id_musico: 10, id_disco: 56 },
        { nombre_cancion: "Exilios", id_musico: 10, id_disco: 56 },
        { nombre_cancion: "La Tropeada", id_musico: 10, id_disco: 56 }
      ]);
    });
};
