/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = function (knex) {
  return knex("canciones").del()
    .then(function () {
      return knex("canciones").insert([
        { nombre_cancion: "Carretera Perdida", id_musicos: 1, id_discos: 1 },
        { nombre_cancion: "Mincho Bar", id_musicos: 1, id_discos: 2 },
        { nombre_cancion: "La Plegaria del Cuchillo", id_musicos: 1, id_discos: 3 },
        { nombre_cancion: "A Cartas Vistas", id_musicos: 1, id_discos: 4 },
        { nombre_cancion: "Buitres", id_musicos: 1, id_discos: 1 },
        { nombre_cancion: "El Tercer Deseo", id_musicos: 1, id_discos: 4 },
        { nombre_cancion: "Besos", id_musicos: 1, id_discos: 2 },
        { nombre_cancion: "Yo No Voy a Morir", id_musicos: 1, id_discos: 1 },
        { nombre_cancion: "Afuera la Lluvia", id_musicos: 1, id_discos: 5 },
        { nombre_cancion: "Condenado el Corazón", id_musicos: 1, id_discos: 6 },
        { nombre_cancion: "Amores Como el Nuestro", id_musicos: 2, id_discos: 7 },
        { nombre_cancion: "Polvo de Estrellas", id_musicos: 2, id_discos: 8 },
        { nombre_cancion: "Sin Sentimiento", id_musicos: 2, id_discos: 9 },
        { nombre_cancion: "La Piscina", id_musicos: 2, id_discos: 10 },
        { nombre_cancion: "Telepatía", id_musicos: 2, id_discos: 11 },
        { nombre_cancion: "Hechizo de Luna", id_musicos: 2, id_discos: 8 },
        { nombre_cancion: "Sobredosis", id_musicos: 2, id_discos: 12 },
        { nombre_cancion: "Mi Mundo, Tú", id_musicos: 2, id_discos: 13 },
        { nombre_cancion: "Un Terremoto de Amor", id_musicos: 2, id_discos: 14 },
        { nombre_cancion: "Piénsalo Dos Veces", id_musicos: 2, id_discos: 15 },
        { nombre_cancion: "Mi País", id_musicos: 3, id_discos: 16 },
        { nombre_cancion: "Muriendo de Plena", id_musicos: 3, id_discos: 16 },
        { nombre_cancion: "Cha Cha, Muchacha", id_musicos: 3, id_discos: 16 },
        { nombre_cancion: "Candombe para Gardel", id_musicos: 3, id_discos: 17 },
        { nombre_cancion: "Las Manzanas", id_musicos: 3, id_discos: 18 },
        { nombre_cancion: "Será Posible", id_musicos: 3, id_discos: 19 },
        { nombre_cancion: "Ayer Te Vi", id_musicos: 3, id_discos: 20 },
        { nombre_cancion: "Terapia de Murga", id_musicos: 3, id_discos: 19 },
        { nombre_cancion: "Solo Se Trata de Vivir", id_musicos: 3, id_discos: 21 },
        { nombre_cancion: "Amandote", id_musicos: 4, id_discos: 22 },
        { nombre_cancion: "Ciega, Sordomuda", id_musicos: 4, id_discos: 23 },
        { nombre_cancion: "Inevitable", id_musicos: 4, id_discos: 23 },
        { nombre_cancion: "Antologia", id_musicos: 4, id_discos: 23 },
        { nombre_cancion: "Estoy Aquí", id_musicos: 4, id_discos: 24 },
        { nombre_cancion: "Pies Descalzos, Sueños Blancos", id_musicos: 4, id_discos: 24 },
        { nombre_cancion: "Ojos Asi", id_musicos: 4, id_discos: 24 },
        { nombre_cancion: "Si Te Vas", id_musicos: 4, id_discos: 23 },
        { nombre_cancion: "Loba", id_musicos: 4, id_discos: 23 },
        { nombre_cancion: "Donde Están Los Ladrones", id_musicos: 4, id_discos: 25 },
        { nombre_cancion: "Que Me Quedes Tú", id_musicos: 5, id_discos: 23 },
        { nombre_cancion: "Con Altura", id_musicos: 5, id_discos: 26 },
        { nombre_cancion: "Bizcochito", id_musicos: 5, id_discos: 27 },
        { nombre_cancion: "Despechá", id_musicos: 5, id_discos: 28 },
        { nombre_cancion: "La Fama", id_musicos: 5, id_discos: 28 },
        { nombre_cancion: "Malamente", id_musicos: 5, id_discos: 28 },
        { nombre_cancion: "Saoko", id_musicos: 5, id_discos: 29 },
        { nombre_cancion: "Beso", id_musicos: 5, id_discos: 28 },
        { nombre_cancion: "Pienso en tu mirá", id_musicos: 5, id_discos: 30 },
        { nombre_cancion: "Tuya", id_musicos: 5, id_discos: 29 },
        { nombre_cancion: "Llylm", id_musicos: 6, id_discos: 31 },
        { nombre_cancion: "Lo Siento", id_musicos: 6, id_discos: 32 },
        { nombre_cancion: "A Ella", id_musicos: 6, id_discos: 33 },
        { nombre_cancion: "Solo Tu y Yo", id_musicos: 6, id_discos: 34 },
        { nombre_cancion: "Inocente", id_musicos: 6, id_discos: 35 },
        { nombre_cancion: "En un lugar un niño", id_musicos: 6, id_discos: 36 },
        { nombre_cancion: "Oncemil", id_musicos: 6, id_discos: 37 },
        { nombre_cancion: "Que Digan Lo Que Quieran", id_musicos: 6, id_discos: 38 },
        { nombre_cancion: "Mi Primer Amor", id_musicos: 6, id_discos: 39 },
        { nombre_cancion: "Amarte No Se Olvida", id_musicos: 7, id_discos: 40 },
        { nombre_cancion: "Santa Noche", id_musicos: 7, id_discos: 41 },
        { nombre_cancion: "Paint It Black", id_musicos: 7, id_discos: 42 },
        { nombre_cancion: "Sympathy For The Devil", id_musicos: 7, id_discos: 43 },
        { nombre_cancion: "Start Me Up", id_musicos: 7, id_discos: 44 },
        { nombre_cancion: "Angie", id_musicos: 7, id_discos: 45 },
        { nombre_cancion: "Under My Thumb", id_musicos: 7, id_discos: 46 },
        { nombre_cancion: "You Can't Always Get What You Want", id_musicos: 7, id_discos: 47 },
        { nombre_cancion: "Ruby Tuesday", id_musicos: 7, id_discos: 44 },
        { nombre_cancion: "Wild Horses", id_musicos: 7, id_discos: 48 },
        { nombre_cancion: "Satisfaction", id_musicos: 8, id_discos: 49 },
        { nombre_cancion: "Brown Sugar", id_musicos: 8, id_discos: 50 },
        { nombre_cancion: "Leave The Door Open", id_musicos: 8, id_discos: 50 },
        { nombre_cancion: "Smokin Out The Window", id_musicos: 8, id_discos: 50 },
        { nombre_cancion: "After Last Night Night", id_musicos: 8, id_discos: 50 },
        { nombre_cancion: "Skate", id_musicos: 8, id_discos: 50 },
        { nombre_cancion: "Love's Train", id_musicos: 8, id_discos: 50 },
        { nombre_cancion: "Fly As Me", id_musicos: 8, id_discos: 50 },
        { nombre_cancion: "Blast Off", id_musicos: 8, id_discos: 50 },
        { nombre_cancion: "Put On A Smile", id_musicos: 8, id_discos: 50 },
        { nombre_cancion: "777", id_musicos: 9, id_discos: 51 },
        { nombre_cancion: "Silk Sonic Intro", id_musicos: 9, id_discos: 51 },
        { nombre_cancion: "Velha Infancia", id_musicos: 9, id_discos: 51 },
        { nombre_cancion: "Já Sei Namorar", id_musicos: 9, id_discos: 51 },
        { nombre_cancion: "Carnavália", id_musicos: 9, id_discos: 51 },
        { nombre_cancion: "Passe Em Casa", id_musicos: 9, id_discos: 51 },
        { nombre_cancion: "É Vocé", id_musicos: 9, id_discos: 51 },
        { nombre_cancion: "Diáspora", id_musicos: 9, id_discos: 51 },
        { nombre_cancion: "Um a Um", id_musicos: 9, id_discos: 51 },
        { nombre_cancion: "Carnalismo", id_musicos: 10, id_discos: 52 },
        { nombre_cancion: "Anjo de Guarda", id_musicos: 10, id_discos: 52 },
        { nombre_cancion: "O Amor É Feio", id_musicos: 10, id_discos: 53 },
        { nombre_cancion: "Milagro", id_musicos: 10, id_discos: 54 },
        { nombre_cancion: "Santamarta", id_musicos: 10, id_discos: 55 },
        { nombre_cancion: "Zumba Que Zumba-En Vivo", id_musicos: 10, id_discos: 56 },
        { nombre_cancion: "La Martín Aranda", id_musicos: 10, id_discos: 55 },
        { nombre_cancion: "Ocho Letras", id_musicos: 10, id_discos: 57 },
        { nombre_cancion: "Peón Rural", id_musicos: 10, id_discos: 56 },
        { nombre_cancion: "Cuando Cante el Gallo Azul", id_musicos: 10, id_discos: 56 },
        { nombre_cancion: "Algo Habrán Hecho", id_musicos: 10, id_discos: 56 },
        { nombre_cancion: "Exilios", id_musicos: 10, id_discos: 56 },
        { nombre_cancion: "La Tropeada", id_musicos: 10, id_discos: 56 }
      ]);
    });
};
